-- 火山云 GPU 平台售价配置。火山实际价仍以实时目录为准，本表只保存对客售价。
CREATE TABLE IF NOT EXISTS volcano_gpu_sale_price (
    id               BIGINT NOT NULL AUTO_INCREMENT COMMENT '售价配置ID',
    region_code      VARCHAR(64) NOT NULL COMMENT '火山云地域编码',
    instance_type_id VARCHAR(128) NOT NULL COMMENT '火山云实例规格ID',
    gpu_model        VARCHAR(64) NOT NULL COMMENT 'GPU型号快照',
    gpu_memory       VARCHAR(32) DEFAULT NULL COMMENT 'GPU显存快照',
    gpu_count        INT NOT NULL DEFAULT 0 COMMENT '实例GPU卡数快照',
    billing_type     VARCHAR(16) NOT NULL COMMENT '计费类型 on_demand/hourly/daily/weekly/monthly',
    upstream_price   DECIMAL(12,4) DEFAULT NULL COMMENT '保存时火山实际价快照',
    sale_price       DECIMAL(12,4) NOT NULL COMMENT '平台售价',
    currency         VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    status           TINYINT(1) NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用',
    remark           VARCHAR(256) DEFAULT NULL COMMENT '备注',
    create_by        VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    create_by_id     BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by        VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    update_by_id     BIGINT DEFAULT NULL COMMENT '更新人ID',
    update_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    del_flag         TINYINT(1) NOT NULL DEFAULT 0 COMMENT '删除标记 0正常 1删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_region_instance_billing (region_code, instance_type_id, billing_type),
    INDEX idx_region_billing (region_code, billing_type),
    INDEX idx_instance_type (instance_type_id),
    INDEX idx_gpu_model (gpu_model),
    CONSTRAINT chk_volcano_sale_price CHECK (sale_price > 0),
    CONSTRAINT chk_volcano_upstream_price CHECK (upstream_price IS NULL OR upstream_price >= 0),
    CONSTRAINT chk_volcano_currency CHECK (currency = 'CNY'),
    CONSTRAINT chk_volcano_billing_type CHECK (billing_type IN ('on_demand', 'hourly', 'daily', 'weekly', 'monthly')),
    CONSTRAINT chk_volcano_price_status CHECK (status IN (0, 1)),
    CONSTRAINT chk_volcano_price_del_flag CHECK (del_flag IN (0, 1))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '火山云GPU平台售价配置表';
