CREATE TABLE IF NOT EXISTS sys_customer_gpu_pod (
    id                  BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    customer_id         BIGINT NOT NULL COMMENT '客户ID',
    order_id            BIGINT COMMENT '关联订单ID',
    order_source_uid    VARCHAR(64) COMMENT '订单资源UID',
    instance_id         VARCHAR(64) NOT NULL COMMENT 'GPU Pod实例ID',
    instance_name       VARCHAR(128) COMMENT '实例名称',
    status              VARCHAR(32) NOT NULL COMMENT '状态',
    region_code         VARCHAR(32) NOT NULL COMMENT '地区编码',
    region_name         VARCHAR(64) COMMENT '地区名称',
    zone_code           VARCHAR(32) COMMENT '可用区编码',
    zone_name           VARCHAR(64) COMMENT '可用区名称',
    gpu_model           VARCHAR(64) NOT NULL COMMENT 'GPU型号',
    gpu_count           INT NOT NULL DEFAULT 1 COMMENT 'GPU数量',
    gpu_memory          VARCHAR(32) COMMENT 'GPU显存',
    cpu_cores           INT NOT NULL COMMENT 'CPU核数',
    memory_size         VARCHAR(32) NOT NULL COMMENT '内存大小',
    system_disk_size    INT COMMENT '系统盘大小(GB)',
    data_disk_size      INT COMMENT '数据盘大小(GB)',
    image_url           VARCHAR(256) COMMENT '镜像地址',
    billing_mode        VARCHAR(32) NOT NULL COMMENT '计费模式',
    billing_status      VARCHAR(32) COMMENT '计费状态',
    price_per_hour      DECIMAL(10, 2) COMMENT '每小时价格',
    create_time         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    start_time          DATETIME COMMENT '启动时间',
    stop_time           DATETIME COMMENT '停止时间',
    release_time        DATETIME COMMENT '释放时间',
    expire_time         DATETIME COMMENT '到期时间',
    scheduled_shutdown_time DATETIME COMMENT '定时关机时间',
    ssh_host            VARCHAR(256) COMMENT 'SSH主机',
    ssh_port            INT DEFAULT 22 COMMENT 'SSH端口',
    ssh_username        VARCHAR(64) COMMENT 'SSH用户名',
    ssh_password        VARCHAR(256) COMMENT 'SSH密码（加密）',
    extra_info          TEXT COMMENT '扩展信息JSON',
    create_by           VARCHAR(64),
    create_by_id        BIGINT,
    update_by           VARCHAR(64),
    update_by_id        BIGINT,
    update_time         DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    del_flag            TINYINT(1) DEFAULT 0,
    INDEX idx_customer_id (customer_id),
    INDEX idx_instance_id (instance_id),
    INDEX idx_status (status),
    INDEX idx_region_code (region_code),
    INDEX idx_create_time (create_time),
    INDEX idx_expire_time (expire_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户GPU Pod实例表';
